In [3]:
from scipy import signal as sg
import numpy as np

In [5]:
a = b = np.arange(25).reshape((5, 5))

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 2D Convolution

In [11]:
sg.convolve2d(a, b)

array([[   0,    0,    1,    4,   10,   20,   25,   24,   16],
       [   0,   10,   32,   68,  120,  140,  140,  118,   72],
       [  25,   80,  168,  292,  455,  460,  420,  332,  193],
       [ 100,  260,  484,  776, 1140, 1080,  940,  716,  404],
       [ 250,  600, 1055, 1620, 2300, 2100, 1775, 1320,  730],
       [ 500, 1100, 1804, 2616, 3540, 3080, 2500, 1796,  964],
       [ 625, 1340, 2148, 3052, 4055, 3460, 2760, 1952, 1033],
       [ 600, 1270, 2012, 2828, 3720, 3140, 2480, 1738,  912],
       [ 400,  840, 1321, 1844, 2410, 2020, 1585, 1104,  576]])

### 2D Corelation

In [12]:
sg.correlate2d(a, b)

array([[   0,   24,   71,  140,  230,  220,  191,  144,   80],
       [ 120,  278,  472,  700,  960,  820,  652,  458,  240],
       [ 335,  712, 1128, 1580, 2065, 1700, 1308,  892,  455],
       [ 620, 1276, 1964, 2680, 3420, 2760, 2084, 1396,  700],
       [ 950, 1920, 2905, 3900, 4900, 3900, 2905, 1920,  950],
       [ 700, 1396, 2084, 2760, 3420, 2680, 1964, 1276,  620],
       [ 455,  892, 1308, 1700, 2065, 1580, 1128,  712,  335],
       [ 240,  458,  652,  820,  960,  700,  472,  278,  120],
       [  80,  144,  191,  220,  230,  140,   71,   24,    0]])

### For 3D Matrix

In [13]:
a = b = np.arange(125).reshape((5, 5, 5))

In [14]:
sg.convolve(a, b)

array([[[     0,      0,      1,      4,     10,     20,     25,     24,
             16],
        [     0,     10,     32,     68,    120,    140,    140,    118,
             72],
        [    25,     80,    168,    292,    455,    460,    420,    332,
            193],
        [   100,    260,    484,    776,   1140,   1080,    940,    716,
            404],
        [   250,    600,   1055,   1620,   2300,   2100,   1775,   1320,
            730],
        [   500,   1100,   1804,   2616,   3540,   3080,   2500,   1796,
            964],
        [   625,   1340,   2148,   3052,   4055,   3460,   2760,   1952,
           1033],
        [   600,   1270,   2012,   2828,   3720,   3140,   2480,   1738,
            912],
        [   400,    840,   1321,   1844,   2410,   2020,   1585,   1104,
            576]],

       [[     0,     50,    152,    308,    520,    540,    500,    398,
            232],
        [   250,    620,   1114,   1736,   2490,   2280,   1930,   1436,
            794

In [15]:
sg.correlate(a, b)

array([[[     0,    124,    371,    740,   1230,   1220,   1091,    844,
            480],
        [   620,   1478,   2572,   3900,   5460,   4820,   3952,   2858,
           1540],
        [  1835,   4012,   6528,   9380,  12565,  10700,   8508,   5992,
           3155],
        [  3620,   7676,  12164,  17080,  22420,  18760,  14684,  10196,
           5300],
        [  5950,  12420,  19405,  26900,  34900,  28900,  22405,  15420,
           7950],
        [  5700,  11796,  18284,  25160,  32420,  26680,  20564,  14076,
           7220],
        [  4955,  10192,  15708,  21500,  27565,  22580,  17328,  11812,
           6035],
        [  3740,   7658,  11752,  16020,  20460,  16700,  12772,   8678,
           4420],
        [  2080,   4244,   6491,   8820,  11230,   9140,   6971,   4724,
           2400]],

       [[  3100,   6398,   9892,  13580,  17460,  14340,  11032,   7538,
           3860],
        [  7190,  14756,  22694,  31000,  39670,  32440,  24854,  16916,
           8630

### Fast Fourier Transform

In [16]:
sg.fftconvolve(a, b)

array([[[ 1.50319263e-12,  1.95793998e-13,  1.00000000e+00,
          4.00000000e+00,  1.00000000e+01,  2.00000000e+01,
          2.50000000e+01,  2.40000000e+01,  1.60000000e+01],
        [-5.62118253e-12,  1.00000000e+01,  3.20000000e+01,
          6.80000000e+01,  1.20000000e+02,  1.40000000e+02,
          1.40000000e+02,  1.18000000e+02,  7.20000000e+01],
        [ 2.50000000e+01,  8.00000000e+01,  1.68000000e+02,
          2.92000000e+02,  4.55000000e+02,  4.60000000e+02,
          4.20000000e+02,  3.32000000e+02,  1.93000000e+02],
        [ 1.00000000e+02,  2.60000000e+02,  4.84000000e+02,
          7.76000000e+02,  1.14000000e+03,  1.08000000e+03,
          9.40000000e+02,  7.16000000e+02,  4.04000000e+02],
        [ 2.50000000e+02,  6.00000000e+02,  1.05500000e+03,
          1.62000000e+03,  2.30000000e+03,  2.10000000e+03,
          1.77500000e+03,  1.32000000e+03,  7.30000000e+02],
        [ 5.00000000e+02,  1.10000000e+03,  1.80400000e+03,
          2.61600000e+03,  3.540000