In [1]:
import scipy.integrate as ig

## Definite Integration

### Single Integration

In [9]:
x3 = lambda x: x**3
print(ig.quad(x3, 0, 3))

(20.249999999999996, 2.2482016248659415e-13)


### Double Integration

In [10]:
func = lambda y, x: x*y** 3 
a = ig.dblquad(func, 0, 3, lambda x: 0, lambda x: 2)
a

(18.0, 1.9984014443252818e-13)

### Triple Integration

In [11]:
func = lambda z, y, x: x*y*z
a = ig.tplquad(func, 0, 2, lambda x: 0, lambda x: 2, lambda x, y: 0, lambda x, y: 2)
a

(7.999999999999999, 8.881784197001251e-14)

## Numerical Techniques(CONM: Computer Oriented Numerical Methods)

In [12]:
import numpy as np

In [13]:
a = np.arange(9).reshape((3, 3)) 

### Trapazoidal Rule

In [15]:
ig.trapz(a, axis=0)

array([ 6.,  8., 10.])

In [16]:
ig.trapz(a, axis=1)

array([ 2.,  8., 14.])

In [21]:
ig.trapz(a, axis=-1)

array([ 2.,  8., 14.])

### Cumalative Trapazoidal Rule

In [18]:
ig.cumtrapz(a, axis=0)

array([[ 1.5,  2.5,  3.5],
       [ 6. ,  8. , 10. ]])

In [19]:
ig.cumtrapz(a, axis=1)

array([[ 0.5,  2. ],
       [ 3.5,  8. ],
       [ 6.5, 14. ]])

In [20]:
ig.cumtrapz(a, axis=-1)

array([[ 0.5,  2. ],
       [ 3.5,  8. ],
       [ 6.5, 14. ]])

### Simpson's Rule

In [22]:
ig.simps(a, axis=0)

array([ 6.,  8., 10.])

In [23]:
ig.simps(a, axis=1)

array([ 2.,  8., 14.])

In [24]:
ig.simps(a, axis=-1)

array([ 2.,  8., 14.])

### Romberg's Rule

In [25]:
ig.romb(a, axis=0)

array([ 6.,  8., 10.])

In [26]:
ig.romb(a, axis=1)

array([ 2.,  8., 14.])

In [27]:
ig.romb(a, axis=-1)

array([ 2.,  8., 14.])