In [1]:
import scipy.constants

# Constants in Scipy

In [2]:
scipy.constants.pi

3.141592653589793

In [3]:
scipy.constants.golden_ratio

1.618033988749895

In [4]:
scipy.constants.c

299792458.0

In [5]:
scipy.constants.mu_0

1.2566370614359173e-06

In [6]:
scipy.constants.epsilon_0

8.854187817620389e-12

In [7]:
scipy.constants.h

6.62607004e-34

In [8]:
scipy.constants.G

6.67408e-11

In [9]:
scipy.constants.g

9.80665

# Linear Algebra

In [12]:
import scipy.linalg as la
import numpy as np

## Finding Inverse of a matrix

In [17]:
x = np.array([[1, 2, 3], [5, 6, 7], [9, 0, 1]])
x

array([[1, 2, 3],
       [5, 6, 7],
       [9, 0, 1]])

In [19]:
x_inv = la.inv(x)
x_inv

array([[-0.15,  0.05,  0.1 ],
       [-1.45,  0.65, -0.2 ],
       [ 1.35, -0.45,  0.1 ]])

## Solving a system of Linear Equations

In [21]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]])
b = np.array([-4, 9, 5])
la.solve(a, b)

array([2., 1., 3.])

## Compute the determinant

In [22]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]])
la.det(a)

-68.99999999999999

## Norm Of a matrix

In [23]:
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]])
la.norm(a)

8.54400374531753

## Upper and Lower Triangular of a matrix

In [26]:
a = np.arange(36).reshape((6, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [27]:
la.tril(a, k=0)

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  7,  0,  0,  0,  0],
       [12, 13, 14,  0,  0,  0],
       [18, 19, 20, 21,  0,  0],
       [24, 25, 26, 27, 28,  0],
       [30, 31, 32, 33, 34, 35]])

In [28]:
la.triu(a, k=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10, 11],
       [ 0,  0, 14, 15, 16, 17],
       [ 0,  0,  0, 21, 22, 23],
       [ 0,  0,  0,  0, 28, 29],
       [ 0,  0,  0,  0,  0, 35]])

## Decomposition Of Matrix

### LU Decomposition

In [30]:
a = np.arange(49).reshape((7, 7))
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [32]:
p, l, u = la.lu(a)

In [33]:
# Permutation Matrix
p

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.]])

In [34]:
# Lower Components
l

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 8.33333333e-01,  1.66666667e-01,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.66666667e-01,  8.33333333e-01,  1.42857143e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.66666667e-01,  3.33333333e-01,  5.00000000e-01,
         5.00000000e-01,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 3.33333333e-01,  6.66666667e-01,  2.14285714e-01,
        -3.33066907e-16,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 5.00000000e-01,  5.00000000e-01, -0.00000000e+00,
         0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         1.0000000

In [35]:
# Upper Components
u

array([[ 4.20000000e+01,  4.30000000e+01,  4.40000000e+01,
         4.50000000e+01,  4.60000000e+01,  4.70000000e+01,
         4.80000000e+01],
       [ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  4.00000000e+00,  5.00000000e+00,
         6.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.10862447e-15,
        -6.21724894e-15, -9.32587341e-15, -1.24344979e-14,
        -1.55431223e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.22044605e-16,  4.44089210e-16,  2.22044605e-16,
        -1.23259516e-31],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.22044605e-16, -2.22044605e-16,
         6.16297582e-32],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
        -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.0000000

###  QR Decomposition

In [42]:
a = np.arange(9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
q, r = la.qr(a)

In [44]:
q

array([[ 0.        ,  0.91287093,  0.40824829],
       [-0.4472136 ,  0.36514837, -0.81649658],
       [-0.89442719, -0.18257419,  0.40824829]])

In [45]:
r

array([[-6.70820393e+00, -8.04984472e+00, -9.39148551e+00],
       [ 0.00000000e+00,  1.09544512e+00,  2.19089023e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.65307819e-16]])

### RQ Decomposition

In [46]:
a = np.arange(9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
r, q = la.rq(a)

In [48]:
r

array([[-1.21153320e-16,  1.20402011e+00, -1.88423342e+00],
       [ 0.00000000e+00,  6.02010056e-01, -7.04539452e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.22065556e+01]])

In [49]:
q

array([[ 0.40824829, -0.81649658,  0.40824829],
       [-0.76923507, -0.06689001,  0.63545506],
       [-0.49153915, -0.57346234, -0.65538554]])